// Users
export const CURRENT_USER = "CURRENT_USER";
export const SET_AUTHORIZATION = "SET_AUTHORIZATION";
export const SET_INVITE_NOTIFICATION = "SET_INVITE_NOTIFICATION";
export const SET_IS_ONLINE = "SET_IS_ONLINE";
// Projects
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const SET_PROJECT_BOARDS = "SET_PROJECT_BOARDS";
export const CLEAR_PROJECT_STATE = "CLEAR_PROJECT_STATE";
// Issues
export const SET_ISSUES = "SET_ISSUES";
export const SET_ISSUE = "SET_ISSUE";
// Issue Comments
export const SET_ISSUE_COMMENTS = "SET_ISSUE_COMMENTS";
